#!/usr/bin/env bash

if [ $# -lt 1 ] || [ $1 == "-h" ] || [ $1 == "--help" ]; then
    echo "Usage: $0 <Name> [directory=./]"
    exit 0
fi

output_dir="./"

if [ $# -gt 1 ]; then
    output_dir="$2"
fi

mkdir -p "$output_dir"
current_dir=$(pwd)
cd "$output_dir"
dotnet new console -o "$1"
cd "$current_dir"
project_dir="$output_dir/$1"
if [ -f "$project_dir/Program.cs" ]; then
    rm -f "$project_dir/Program.cs"
fi
echo -e "using System;\n\nnamespace $1\n{\n    class Application\n    {\n        static int Main(string[] args)\n        {\n            if(args.Length < 1)\n            {\n                /*Print usage*/\n                System.Console.WriteLine(\"Usage: {0} [OPTIONS]\", Environment.GetCommandLineArgs()[0]);\n                return 0;\n            }\n            //Otherwise run program\n\n            return 0;\n        }\n    }\n}\n" > "$project_dir/Application.cs"
echo "IyEvdXNyL2Jpbi9lbnYgYmFzaAoKU0NSSVBUX0RJUj0kKCBjZCAtLSAiJCggZGlybmFtZSAtLSAiJHtCQVNIX1NPVVJDRVswXX0iICkiICY+IC9kZXYvbnVsbCAmJiBwd2QgKQoKaWYgWyAkIyAtbHQgMSBdIHx8IFsgJDEgPT0gIi1oIiBdIHx8IFsgJDEgPT0gIi0taGVscCIgXTsgdGhlbgogICAgZWNobyAiVXNhZ2U6ICQwIDxSZWxlYXNlfERlYnVnPiIKICAgIGV4aXQgMApmaQoKaWYgW1sgIiQxIiA9PSAiUmVsZWFzZSIgfHwgIiQxIiA9PSAiRGVidWciIF1dOyB0aGVuCiAgICBjdXJyZW50X2Rpcj0kKHB3ZCkKICAgIGNkICIkU0NSSVBUX0RJUiIKICAgIGRvdG5ldF92ZXJzaW9uPSQoZG90bmV0IC0tdmVyc2lvbiB8IGN1dCAtZCcuJyAtZiAxLTIpCiAgICBkb3RuZXQgYnVpbGQgLWMgIiQxIiAmJiBkb3RuZXQgcHVibGlzaCAtZiAibmV0JGRvdG5ldF92ZXJzaW9uIiAtYyAiJDEiCiAgICBjZCAiJGN1cnJlbnRfZGlyIgplbHNlCiAgICBlY2hvICJUeXBlICdSZWxlYXNlJyBmb3IgYnVpbGRpbmcgcmVsZWFzZSB2ZXJzaW9uIG9yICdEZWJ1ZyBmb3IgZGVidWcgdmVyc2lvbiEiCmZp" | base64 -d > "$project_dir/build"
chmod 755 "$project_dir/build"
echo "IyEvdXNyL2Jpbi9lbnYgYmFzaAoKU0NSSVBUX0RJUj0kKCBjZCAtLSAiJCggZGlybmFtZSAtLSAiJHtCQVNIX1NPVVJDRVswXX0iICkiICY+IC9kZXYvbnVsbCAmJiBwd2QgKQoiJFNDUklQVF9ESVIvYnVpbGQiIFJlbGVhc2UK" | base64 -d > "$project_dir/build_release"
chmod 755 "$project_dir/build_release"
echo "IyEvdXNyL2Jpbi9lbnYgYmFzaAoKU0NSSVBUX0RJUj0kKCBjZCAtLSAiJCggZGlybmFtZSAtLSAiJHtCQVNIX1NPVVJDRVswXX0iICkiICY+IC9kZXYvbnVsbCAmJiBwd2QgKQoiJFNDUklQVF9ESVIvYnVpbGQiIERlYnVn" | base64 -d > "$project_dir/build_debug"
chmod 755 "$project_dir/build_debug"
echo "IyEvdXNyL2Jpbi9lbnYgYmFzaAoKU0NSSVBUX0RJUj0kKCBjZCAtLSAiJCggZGlybmFtZSAtLSAiJHtCQVNIX1NPVVJDRVswXX0iICkiICY+IC9kZXYvbnVsbCAmJiBwd2QgKQoKaWYgWyAkIyAtbHQgMSBdIHx8IFsgJDEgPT0gIi1oIiBdIHx8IFsgJDEgPT0gIi0taGVscCIgXTsgdGhlbgogICAgZWNobyAiVXNhZ2U6ICQwIDxSZWxlYXNlfERlYnVnPiIKICAgIGV4aXQgMApmaQoKcHJvamVjdF9uYW1lPSQoYmFzZW5hbWUgJFNDUklQVF9ESVIpCmRvdG5ldF92ZXJzaW9uPSQoZG90bmV0IC0tdmVyc2lvbiB8IGN1dCAtZCcuJyAtZiAxLTIpCnByb2plY3RfcnVudGltZT0kKGZpbmQgJFNDUklQVF9ESVIgLWlyZWdleCAiLiokMS4qJGRvdG5ldF92ZXJzaW9uLiovcHVibGlzaC8kcHJvamVjdF9uYW1lXCQiKQppZiBbIC16ICIkcHJvamVjdF9ydW50aW1lIiBdOyB0aGVuCiAgICBlY2hvIC1lICJFUlJPUjogTWlzc2luZyAkMSBiaW5hcnkhXG5Gcm9tICRTQ1JJUFRfRElSXG5SdW4gLi9idWlsZF9yZWxlYXNlIG9yIC4vYnVpbGRfZGVidWcgc2NyaXB0IGJlZm9yZSBydW5uaW5nIHRoZSBhcHBsaWNhdGlvbiEiCmVsc2UKICAgIGZvciBydW50aW1lX3BhdGggaW4gJHByb2plY3RfcnVudGltZTsgZG8KICAgICAgICBzaGlmdAogICAgICAgICIkcnVudGltZV9wYXRoIiAkQAogICAgICAgIGJyZWFrCiAgICBkb25lCmZpCg==" | base64 -d > "$project_dir/run"
chmod 755 "$project_dir/run"
echo "IyEvdXNyL2Jpbi9lbnYgYmFzaAoKU0NSSVBUX0RJUj0kKCBjZCAtLSAiJCggZGlybmFtZSAtLSAiJHtCQVNIX1NPVVJDRVswXX0iICkiICY+IC9kZXYvbnVsbCAmJiBwd2QgKQoiJFNDUklQVF9ESVIvcnVuIiBSZWxlYXNlICRA" | base64 -d > "$project_dir/run_release"
chmod 755 "$project_dir/run_release"
echo "IyEvdXNyL2Jpbi9lbnYgYmFzaAoKU0NSSVBUX0RJUj0kKCBjZCAtLSAiJCggZGlybmFtZSAtLSAiJHtCQVNIX1NPVVJDRVswXX0iICkiICY+IC9kZXYvbnVsbCAmJiBwd2QgKQoiJFNDUklQVF9ESVIvcnVuIiBEZWJ1ZyAkQAo=" | base64 -d > "$project_dir/run_debug"
chmod 755 "$project_dir/run_debug"
echo "IyEvdXNyL2Jpbi9lbnYgYmFzaAoKU0NSSVBUX0RJUj0kKCBjZCAtLSAiJCggZGlybmFtZSAtLSAiJHtCQVNIX1NPVVJDRVswXX0iICkiICY+IC9kZXYvbnVsbCAmJiBwd2QgKQoKaWYgWyAkIyAtbHQgMSBdIHx8IFsgJDEgPT0gIi1oIiBdIHx8IFsgJDEgPT0gIi0taGVscCIgXTsgdGhlbgogICAgZWNobyAiVXNhZ2U6ICQwIDxBbGx8UmVsZWFzZXxEZWJ1Zz4iCiAgICBleGl0IDAKZmkKCmJpbl9kaXI9IiRTQ1JJUFRfRElSL2JpbiIKCmlmIFsgLWQgIiRiaW5fZGlyIiBdOyB0aGVuCiAgICBpZiBbWyAiJDEiID09ICJSZWxlYXNlIiB8fCAiJDEiID09ICJEZWJ1ZyIgXV07IHRoZW4KICAgICAgICBlY2hvICJybSAtciAkYmluX2Rpci8kMSIKICAgICAgICBybSAtciAiJGJpbl9kaXIvJDEiCiAgICBlbGlmIFsgIiQxIiA9PSAiQWxsIiBdOyB0aGVuCiAgICAgICAgaWYgWyAtZCAiJGJpbl9kaXIiIF07IHRoZW4KICAgICAgICAgICAgZWNobyAicm0gLXIgJGJpbl9kaXIiCiAgICAgICAgICAgIHJtIC1yICIkYmluX2RpciIKICAgICAgICBmaQogICAgZWxzZQogICAgICAgIGVjaG8gIlVucmVjb2duaXplZCBvcHRpb246ICQxIgogICAgZmkKZmkK" | base64 -d > "$project_dir/clean"
chmod 755 "$project_dir/clean"

echo "Project created to $project_dir"
